[package]
name = "rs_svg"
version = "0.1.0"
authors = ["djedou"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.65"
djed = {git = "https://github.com/djedou/djed"}
js-sys = "0.3"